---
name: 'Check'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'push'
    uses: SlashNephy/.github/.github/workflows/yarn-run.yml
    permissions:
      contents: 'read'
    with:
      script: 'build'

  lint:
    uses: SlashNephy/.github/.github/workflows/yarn-lint.yml
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name == 'push'
    uses: SlashNephy/.github/.github/workflows/yarn-format.yml
    permissions:
      contents: 'write'
